bot
Naoya-Otani/easylist pull request #64
Opened 2024-03-24 13:55 UTC by lll-kkk-ryuya

- **bot front**
- **Revert "Merge pull request #60 from Naoya-Otani/fix/sort-filter"**
- **bot**

## 関連するタスク

- [タスクへのリンク](https://example.com)

## 実施内容

- このプルリクエストで何を実施したのか？

## 実施しないこと

- このプルリクエストで実施しないことは何か？（ない場合は「なし」と記述する。実施しない場合、いつ実施する予定かを明記する。）

## ユーザーへの利益

- ユーザーの視点から、この変更によって何が向上するのか？（ない場合は「なし」と記述する。）

## ユーザーへの悪影響

- ユーザーの視点から、この変更によって何が悪化するのか？（ない場合は「なし」と記述する。）

## 動作確認

- どのような動作確認を行ったのか？ 結果はどうか？

## その他

- レビュアーへの参考情報（実装上の懸念点や注意事項などがあれば記載する。）

2024-03-25 05:40 UTC, Naoya-Otani requested changes
全体的に、コードがわかりずらい場合を除いてコメントは削除してください。
不要なインデントも削除してください。
それ以外のところは `GOOD JOB👌`です！

2024-03-25 05:40 UTC, Naoya-Otani commented on package.json
> +    "@mui/material": "^5.15.13",
使ってないライブラリはアンインストールしてください！

2024-03-25 05:40 UTC, Naoya-Otani commented on package.json
> +    "tailwindcss": "^3.4.1"
"tailwindcss": "^3.2.7" にダウングレードしてください！

2024-03-25 05:40 UTC, Naoya-Otani commented on src/@types/heroicons.d.ts
> +    export const PaperAirplaneIcon: React.FC<React.SVGProps<SVGSVGElement>>;
型定義ファイルは直接いじらないでください！
多分、いじらなくても使えるはず

2024-03-25 05:40 UTC, Naoya-Otani commented on tailwind.config.js
> +    },
これはどういう意図？

2024-03-25 05:40 UTC, Naoya-Otani commented on src/services/api.ts
> +};
APIエンドポイントは、
`src/pages/api`配下に作成しないと機能しません！

2024-03-25 05:40 UTC, Naoya-Otani commented on src/pages/chat/react-chat-elements.d.ts
> +    // 必要に応じて他のコンポーネントも追加
Chatでしか使わない型に関しては、コンポーネントで型定義を宣言してください！

2024-03-25 05:40 UTC, Naoya-Otani commented on src/components/atoms/icon/Logo.tsx
> +export default Logo;
classNameをpropsで受け取っているのに、空の文字列が代入されているので、そのまま受け取れるようにしましょう。

2024-03-25 05:40 UTC, Naoya-Otani commented on src/components/parts/chat/ChatDisplay.tsx
> +            <div id="message-list" className=" overflow-auto flex-1 w-3/5 p-4 rounded-lg bg-gray-50">
`id="message-list"` は何かに使ってますか？

2024-03-25 05:40 UTC, Naoya-Otani commented on src/components/parts/chat/ChatDisplay.tsx
> +                ))}
恐らく、
Botだと左・人間だと右に MessageBoxを配置するんだと思いますが、
left/rightを直書きしていたら動かないので、三項演算子を使って
sourceの値で条件分岐させましょう

2024-03-25 05:40 UTC, Naoya-Otani commented on src/components/templates/Chat/HeaderChat.tsx
> +export default Header;
なんのためのファイル？

2024-03-25 05:40 UTC, Naoya-Otani commented on src/pages/chat/index.tsx
> +const WEBSOCKET_URL = "ws://127.0.0.1:8000/ws"; // 適切なWebSocketエンドポイントURLに変更してください
環境変数を設定してください！

2024-03-25 05:40 UTC, Naoya-Otani commented on src/pages/chat/index.tsx
> +import Header from "@/src/components/templates/Chat/HeaderChat";
アプリで使われている共通のヘッダーを使ってください（何か意図があれば教えてください）

2024-03-25 05:40 UTC, Naoya-Otani commented on src/pages/chat/index.tsx
> +    source: message.source || 'bot', // sourceが未定義の場合は 'bot' とする
Backend側のDate型と合致してますか？

2024-03-25 05:40 UTC, Naoya-Otani commented on src/services/api.ts
> +const API_BASE_URL = 'http://127.0.0.1:8000'; // あなたのFastAPIサーバーのURL
環境変数を設定してください！

2024-03-25 05:40 UTC, Naoya-Otani commented on tsconfig.json
> +    "typeRoots": ["./node_modules/@types","src/@types"],
？

2024-04-07 05:50 UTC, lll-kkk-ryuya commented on src/pages/chat/index.tsx
> +import Header from "@/src/components/templates/Chat/HeaderChat";
chatのスクロールを行う際に、Headerはスクロールせずchat画面のみをスクロールするため違うファイルに書いています。

2024-04-22 05:38 UTC, lll-kkk-ryuya commented on src/components/templates/Header.tsx
SearchBarの表示を行わないために、falseの際は表示をしない仕様にしています。
通常はtrueなので他には影響ありません

2024-05-06 05:55 UTC, merged